# Generated by Django 5.0.7 on 2024-08-26 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_load_threshold', models.FloatField(default=80.0)),
                ('memory_used_threshold', models.FloatField(default=8.0)),
                ('memory_percent_threshold', models.FloatField(default=80.0)),
                ('network_traffic_sent_threshold', models.BigIntegerField(default=1000000000)),
                ('network_traffic_received_threshold', models.BigIntegerField(default=1000000000)),
                ('device_availability_packet_loss_threshold', models.FloatField(default=10.0)),
                ('device_availability_ping_time_threshold', models.FloatField(default=100.0)),
                ('connected_device_count_threshold', models.IntegerField(default=10)),
                ('app_usage_connections_threshold', models.IntegerField(default=100)),
                ('traceroute_hop_latency_threshold', models.FloatField(default=100.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
