# Generated by Django 5.0.7 on 2024-08-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0002_remove_alertsettings_app_usage_connections_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsettings',
            name='memory_used_threshold',
            field=models.BigIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='alertsettings',
            name='network_traffic_received_threshold',
            field=models.BigIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='alertsettings',
            name='network_traffic_sent_threshold',
            field=models.BigIntegerField(default=1),
        ),
    ]
