# Generated by Django 5.0.7 on 2024-08-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0003_alter_alertsettings_memory_used_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertsettings',
            name='traceroute_hop_latency_notification',
        ),
        migrations.RemoveField(
            model_name='alertsettings',
            name='traceroute_hop_latency_threshold',
        ),
    ]
