# Generated by Django 5.0.7 on 2024-09-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0006_alter_networkipsetting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkipsetting',
            name='subnet',
            field=models.CharField(default='255.255.255.0', max_length=20),
        ),
    ]
