# Generated by Django 5.0.7 on 2024-09-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0007_networkipsetting_subnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkipsetting',
            name='subnet',
            field=models.IntegerField(default=24),
        ),
    ]
